import { useState, useEffect, useMemo, useCallback, useRef } from "react";
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Treemap } from "recharts";

const INITIAL_DATA = [{"id":1,"name":"AccessRC","description":"Affected people registration, program management, connection to cash assistance tools","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Software As A Service","appTechnology":"React Native, React, .Net8, C# (API)","database":"Dont Know","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Disasters Climate and Crises - Caroline Holt","interviewStatus":"Completed","mau":144178,"frequencyOfUse":"Programmatic","primaryUserType":"National Societies","geographicReach":"Global","portfolio":"Membership","department":"DCC, Digital Transformation Department","totalAnnualCost":587800,"size":"L","strategyReco":"To be discussed","status":"","costCenter":"G00365 / Partner/NS","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":3,"strategicPositioning":2,"geographicReachScore":2,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":2,"name":"Adobe Creative Cloud Services","description":"Document/Photo/Image/Media editing","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Transformation Department - Juriaan","interviewStatus":"Completed","mau":500,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"Communications","totalAnnualCost":113117,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00557","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":3,"name":"Adobe Sign","description":"Electronic Signature, Digital Signature","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Transformation Department - Juriaan","interviewStatus":"Completed","mau":2297,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"Legal","totalAnnualCost":169043,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00557","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":4,"name":"Adore Repository","description":"New Document Repository for Publishing","category":"App","archetype":"Internal Management","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"Azure storage","dtdOwner":"Operations unit - Istvan","businessOwner":"Carlota Tarazona, Ekaterina Daummer","interviewStatus":"Completed","mau":2000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":42433,"size":"","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":5,"name":"AlertHub","description":"Published CAP alerts worldwide","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":"Django/Python","database":"PostgreSQL","dtdOwner":"Data unit - Stefano","businessOwner":"Climate, Environment and Resilience - Nathan Cooper","interviewStatus":"Completed","mau":275,"frequencyOfUse":"Daily alerts","primaryUserType":"National Societies","geographicReach":"50+ countries","portfolio":"Membership","department":"IM","totalAnnualCost":760000,"size":"M","strategyReco":"Keep","status":"","costCenter":"G00398","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":3,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":6,"name":"Apple","description":"Master Data Management","category":"App","archetype":"Internal Management","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"MySQL","dtdOwner":"Operations unit - Istvan","businessOwner":"Financial and Administrative Management - Sunil","interviewStatus":"Completed","mau":2,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"all","portfolio":"Secretariat","department":"Finance and Administration","totalAnnualCost":95833,"size":"","strategyReco":"Keep","status":"To be retired","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":7,"name":"Appraisals System","description":"Performance Appraisal for Staff","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"Cornerstone","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Human Resources - Edwin","interviewStatus":"Completed","mau":1700,"frequencyOfUse":"daily","primaryUserType":"IFRC Contracted Staff","geographicReach":"90+ delegations","portfolio":"Secretariat","department":"Human Resources","totalAnnualCost":86529,"size":"M","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":8,"name":"Articulate 360 Training","description":"Creation of E-Training","category":"App","archetype":"Internal Management","subClassification":"Productivity Tools","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"No vertical owner","interviewStatus":"Pending","mau":4,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"Learning","totalAnnualCost":10371,"size":"S","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":9,"name":"AV Media Assets Storage","description":"File Management, Storage","category":"App","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Communications and Content - Benoit","interviewStatus":"Completed","mau":4,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"Communications","totalAnnualCost":42363,"size":"S","strategyReco":"Keep","status":"","costCenter":"C00088","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":10,"name":"Bulletin Board","description":"Information Sharing","category":"App","archetype":"Internal Management","subClassification":"Standard Software","appTechnology":"Microsoft Viva Engage","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Strategic Communications","interviewStatus":"Completed","mau":2251,"frequencyOfUse":"Weekly","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"","totalAnnualCost":14833,"size":"","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":36,"name":"ERP D365 All Modules","description":"Accounts Management","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"X++","database":"MsSQL","dtdOwner":"ERP - Khaled","businessOwner":"Financial and Administrative Management - Sunil","interviewStatus":"Completed","mau":0,"frequencyOfUse":"daily/weekly/monthly","primaryUserType":"Secretariat staff","geographicReach":"191 NS","portfolio":"Secretariat","department":"","totalAnnualCost":5404926,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00557","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":37,"name":"ERP D365 Reporting","description":"Reporting Tool","category":"App","archetype":"Internal Management","subClassification":"Platform as a Service","appTechnology":"X++ and PowerBI/Fabric","database":"MsSQL","dtdOwner":"Data unit - Stefano","businessOwner":"","interviewStatus":"Completed","mau":2500,"frequencyOfUse":"Daily","primaryUserType":"Secretariat ERP Users","geographicReach":"Global","portfolio":"Secretariat","department":"","totalAnnualCost":1487833,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00555","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":43,"name":"Essential Infrastructure","description":"Hosting, Connectivity, Network, Printing, Devices, Cybersecurity","category":"Product","archetype":"Internal Management","subClassification":"Infrastructure","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Transformation Department - Juriaan","interviewStatus":"Completed","mau":2800,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"Digital Transformation Department","totalAnnualCost":1220000,"size":"L","strategyReco":"Keep","status":"","costCenter":"OCH","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":48,"name":"Fleetwave","description":"Fleet Management System","category":"App","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Off the Shelf Software","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Global Humanitarian Services - Cecile Terraz","interviewStatus":"Completed","mau":700,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff and NS","geographicReach":"79 countries","portfolio":"IFRC Network","department":"","totalAnnualCost":107033,"size":"M","strategyReco":"Essential","status":"","costCenter":"C00286","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":55,"name":"GO DREF","description":"All DREF requests channeled via GO","category":"Product","archetype":"IFRC Agility & Decision-Support","subClassification":"Be-Spoke Software","appTechnology":"Django/Python/React","database":"PostgreSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"NSDOC - Luke Caley / Nicolas Boyrie","interviewStatus":"Completed","mau":101000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"","totalAnnualCost":39095,"size":"M","strategyReco":"Essential","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":56,"name":"GO Emergency pages","description":"Key resource for IFRC supported operations","category":"Product","archetype":"IFRC Agility & Decision-Support","subClassification":"Be-Spoke Software","appTechnology":"Django/Python/React","database":"PostgreSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"NSDOC - Luke Caley / Caroline Holt","interviewStatus":"Completed","mau":101000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"","totalAnnualCost":51595,"size":"M","strategyReco":"Essential","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":54,"name":"GO Disaster Field Reports","description":"Key data input from NS on emergency situations","category":"Product","archetype":"IFRC Agility & Decision-Support","subClassification":"Be-Spoke Software","appTechnology":"Django/Python/React","database":"PostgreSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"NSDOC - Luke Caley / Caroline Holt","interviewStatus":"Completed","mau":101000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"","totalAnnualCost":80762,"size":"M","strategyReco":"Keep","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":97,"name":"Office Productivity Tools","description":"O365, Email, Teams, Meeting support, etc.","category":"Product","archetype":"Internal Management","subClassification":"Standard Software","appTechnology":"O365","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Transformation Department - Juriaan","interviewStatus":"Completed","mau":2800,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"Digital Transformation Department","totalAnnualCost":2461667,"size":"L","strategyReco":"Keep","status":"","costCenter":"OCH","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":119,"name":"Universal First Aid App (UFAA)","description":"Life-saving first aid information app","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":"","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Health and Care - Petra Khoury","interviewStatus":"Completed","mau":657098,"frequencyOfUse":"daily","primaryUserType":"Anyone who downloads","geographicReach":"75 countries","portfolio":"Membership","department":"","totalAnnualCost":137833,"size":"M","strategyReco":"Keep","status":"","costCenter":"G00468","fundingOrigin":3,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":15,"name":"Cash 1 2 1","description":"Person in Need registration, assistance delivery, case management","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Software As A Service","appTechnology":"CSS,HTML,JS,TWIG,PHP","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Socio Economic Empowerment - Joseph Oliveros","interviewStatus":"Pending","mau":250000,"frequencyOfUse":"Programmatic","primaryUserType":"National Societies","geographicReach":"Global","portfolio":"Membership","department":"","totalAnnualCost":71667,"size":"L","strategyReco":"Keep","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":22,"name":"Digital Engagement Hub","description":"Affected people Digital communication","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":"Twilio","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Socio Economic Empowerment - Alexandra Sicotte","interviewStatus":"Completed","mau":60658,"frequencyOfUse":"Daily","primaryUserType":"National Societies","geographicReach":"6","portfolio":"Membership","department":"","totalAnnualCost":149238,"size":"L","strategyReco":"Divest","status":"","costCenter":"G00467","fundingOrigin":3,"financialSustainability":2,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":23,"name":"Donation Hub (iRaiser)","description":"Donation collection from IFRC.org users","category":"Product","archetype":"Humanitarian Diplomacy & Positioning","subClassification":"Be-Spoke Software","appTechnology":"","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"SPRM and Comms","interviewStatus":"Completed","mau":80000,"frequencyOfUse":"Daily","primaryUserType":"General public","geographicReach":"Global","portfolio":"IFRC Network","department":"PRD","totalAnnualCost":41833,"size":"S","strategyReco":"Keep","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":18,"name":"COP - Community of Practice","description":"Community of Practice platform","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Software As A Service","appTechnology":"PleK","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"National Society Development","interviewStatus":"Completed","mau":2095,"frequencyOfUse":"Weekly","primaryUserType":"Movement users","geographicReach":"185 NS","portfolio":"IFRC Network","department":"","totalAnnualCost":402000,"size":"M","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":74,"name":"KoboToolkit","description":"Primary / Mobile Data Collection","category":"App","archetype":"Direct Community & Humanitarian Impact","subClassification":"Open Source Software","appTechnology":"Python/Typescript","database":"","dtdOwner":"Data unit - Stefano","businessOwner":"NSDOC","interviewStatus":"Completed","mau":5700,"frequencyOfUse":"Daily","primaryUserType":"National Societies, Secretariat","geographicReach":"181","portfolio":"Membership","department":"","totalAnnualCost":89485,"size":"M","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":3,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":121,"name":"Volunteer Data Mgmt System","description":"Volunteer management through data and digital systems","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":"CiviCRM","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Volunteering, Youth and Education - Adjmal Dulloo","interviewStatus":"Completed","mau":15000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Membership","department":"","totalAnnualCost":41833,"size":"","strategyReco":"Keep","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":3,"strategicPositioning":1,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":46,"name":"FedNet","description":"Intranet/Extranet","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":"Episerver","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"National Society Development","interviewStatus":"Completed","mau":10000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"Communications","totalAnnualCost":23833,"size":"","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":2,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":3,"comments":"Require rapid replacement - data security risks","interviewerComments":"","userNotes":""},
{"id":47,"name":"Financials (Coda)","description":"Organisational Financial System","category":"App","archetype":"Internal Management","subClassification":"Off the Shelf Software","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Financial and Administrative Management - Sunil","interviewStatus":"Completed","mau":50,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"all","portfolio":"Secretariat","department":"Finance and Administration","totalAnnualCost":194933,"size":"L","strategyReco":"Terminate","status":"To be retired","costCenter":"C00557","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":2,"potentialFutureValue":3,"comments":"To be sunset when PBI reports ready","interviewerComments":"","userNotes":""},
{"id":69,"name":"HLS","description":"Procurement, warehousing, and distribution","category":"App","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Global Humanitarian Services - Cecile Terraz","interviewStatus":"Completed","mau":3,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"","totalAnnualCost":56233,"size":"L","strategyReco":"Terminate","status":"To be retired","costCenter":"C00286","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":3,"comments":"Being retired, keep historical records","interviewerComments":"","userNotes":""},
{"id":90,"name":"NSDB Digital Maturity Quick Scan","description":"NS digital capabilities assessment","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"MsSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"Digital Transformation Department - Juriaan","interviewStatus":"Completed","mau":2,"frequencyOfUse":"quarterly","primaryUserType":"IFRC teams","geographicReach":"50 countries","portfolio":"IFRC Network","department":"Digital Transformation Department","totalAnnualCost":8833,"size":"","strategyReco":"Terminate","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":3,"potentialFutureValue":2,"comments":"Migrating to Kobo + PowerBI","interviewerComments":"","userNotes":""},
{"id":14,"name":"Canva","description":"Design tool","category":"Service","archetype":"Internal Management","subClassification":"Productivity Tools","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"No vertical owner","interviewStatus":"Pending","mau":11,"frequencyOfUse":"Every other day","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":7333,"size":"S","strategyReco":"Divest","status":"","costCenter":"Various","fundingOrigin":3,"financialSustainability":3,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":79,"name":"Mentimeter Pro","description":"Interactive Survey During Online Presentation","category":"App","archetype":"Internal Management","subClassification":"Productivity Tools","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"DTD - Juriaan","interviewStatus":"Completed","mau":10,"frequencyOfUse":"Weekly","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"Solferino Academy","totalAnnualCost":9033,"size":"S","strategyReco":"Divest","status":"","costCenter":"Various","fundingOrigin":2,"financialSustainability":2,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":3,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":81,"name":"Miro","description":"Productivity tool","category":"Tool","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Several departments","interviewStatus":"Completed","mau":40,"frequencyOfUse":"Daily","primaryUserType":"Secretariat, NS","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":10333,"size":"S","strategyReco":"Divest","status":"","costCenter":"Various departments","fundingOrigin":3,"financialSustainability":3,"keepLightsOn":3,"strategicPositioning":3,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":101,"name":"Rapid Response Mgmt - Surge","description":"System to manage Surge resources","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Software As A Service","appTechnology":"Molnix","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"DCC - Francisco Maldonado","interviewStatus":"Completed","mau":6000,"frequencyOfUse":"Daily (hourly)","primaryUserType":"IFRC, NS staff, volunteers","geographicReach":"191 NS","portfolio":"Secretariat","department":"","totalAnnualCost":39833,"size":"","strategyReco":"Keep","status":"","costCenter":"G00372","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":104,"name":"RedRoseOne","description":"Cash Distribution System","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Software As A Service","appTechnology":"Django/Python","database":"MySQL","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Socio Economic Empowerment - Joseph Oliveros","interviewStatus":"Completed","mau":0,"frequencyOfUse":"Programmatic","primaryUserType":"National Societies","geographicReach":"Global","portfolio":"Membership","department":"","totalAnnualCost":50833,"size":"","strategyReco":"Keep","status":"","costCenter":"Partner/NS","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":91,"name":"NSDB FDRS (Backend)","description":"Federation-wide databank and reporting system","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"MsSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"Strategic Planning - Rania Alerksoussi","interviewStatus":"Completed","mau":0,"frequencyOfUse":"Daily","primaryUserType":"IFRC, NS, donors, researchers","geographicReach":"200 countries","portfolio":"IFRC Network","department":"","totalAnnualCost":151833,"size":"L","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":44,"name":"eTravel","description":"Travel and Expense Management","category":"Product","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"SAP - Concur","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"Financial and Administrative Management - Sunil","interviewStatus":"Completed","mau":500,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":185833,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00538","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":2,"currentHumReach":3,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":100,"name":"Power BI Analytics","description":"Data Visualisation","category":"App","archetype":"Internal Management","subClassification":"Reporting","appTechnology":"PowerBI","database":"MsSQL","dtdOwner":"Data unit - Stefano","businessOwner":"DTD - Juriaan","interviewStatus":"Completed","mau":2800,"frequencyOfUse":"Daily","primaryUserType":"Secretariat","geographicReach":"150","portfolio":"Secretariat","department":"Digital Transformation Department","totalAnnualCost":389663,"size":"S","strategyReco":"Keep","status":"","costCenter":"C00557","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"Essential for all departments","interviewerComments":"","userNotes":""},
{"id":113,"name":"Swiss Salary","description":"HR Payroll","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"ERP - Khaled","businessOwner":"Human Resources - Edwin","interviewStatus":"Completed","mau":0,"frequencyOfUse":"daily","primaryUserType":"IFRC Contracted Staff","geographicReach":"90+ delegations","portfolio":"Secretariat","department":"","totalAnnualCost":194833,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":12,"name":"C2 Extranet","description":"Replace FedNet for content creation and knowledge sharing","category":"Request for exisitng","archetype":"Humanitarian Diplomacy & Positioning","subClassification":"Be-Spoke Software","appTechnology":"","database":"TBD","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Communications - Vianka Olivero","interviewStatus":"Completed","mau":10000,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"IFRC Network","department":"","totalAnnualCost":1255833,"size":"M","strategyReco":"Cancel (request)","status":"","costCenter":"C00537","fundingOrigin":3,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":1,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":1,"comments":"On hold - lack of funding","interviewerComments":"","userNotes":""},
{"id":41,"name":"ERP Risk Management","description":"Risk Management in D365","category":"Request","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"","database":"","dtdOwner":"ERP - Khaled","businessOwner":"Executive Office","interviewStatus":"Completed","mau":170,"frequencyOfUse":"Weekly/Monthly","primaryUserType":"Secretariat staff","geographicReach":"54","portfolio":"Secretariat","department":"","totalAnnualCost":38833,"size":"","strategyReco":"Cancel (request)","status":"","costCenter":"C","fundingOrigin":3,"financialSustainability":2,"keepLightsOn":3,"strategicPositioning":2,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":106,"name":"SIMPL MVP","description":"Global IFRC security management systems status","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":"","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Global Security Unit - Lars Tangen","interviewStatus":"Completed","mau":250,"frequencyOfUse":"Daily","primaryUserType":"IFRC and PNS security staff","geographicReach":"100+ countries","portfolio":"Secretariat","department":"","totalAnnualCost":507667,"size":"","strategyReco":"To be discussed","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":3,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""},
{"id":102,"name":"RCHIS","description":"Medical Clinic Solution","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":".Net/Xamarin","database":"MsSQL","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Health and Care - Petra Khoury","interviewStatus":"Completed","mau":0,"frequencyOfUse":"daily","primaryUserType":"IFRC, NS","geographicReach":"Egypt deployment","portfolio":"Membership","department":"DCC","totalAnnualCost":95833,"size":"","strategyReco":"To be discussed","status":"","costCenter":"G00501","fundingOrigin":3,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":3,"currentHumReach":3,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":16,"name":"CBS NYSS","description":"Community-based surveillance data platform","category":"Product","archetype":"Direct Community & Humanitarian Impact","subClassification":"Be-Spoke Software","appTechnology":"","database":"","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Health and Care - Petra Khoury","interviewStatus":"Completed","mau":0,"frequencyOfUse":"daily","primaryUserType":"NS","geographicReach":"22 countries","portfolio":"Membership","department":"","totalAnnualCost":191833,"size":"","strategyReco":"To be discussed","status":"","costCenter":"G","fundingOrigin":1,"financialSustainability":1,"keepLightsOn":3,"strategicPositioning":2,"geographicReachScore":2,"currentHumReach":2,"potentialFutureValue":1,"comments":"Maintained by NorCross","interviewerComments":"","userNotes":""},
{"id":42,"name":"espoCRM","description":"Free Self Hosted CRM","category":"App","archetype":"IFRC Agility & Decision-Support","subClassification":"Open Source Software","appTechnology":"PHP","database":"MySQL","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Tbd","interviewStatus":"Completed","mau":20,"frequencyOfUse":"Daily","primaryUserType":"Secretariat, NS","geographicReach":"Ukraine","portfolio":"Membership","department":"","totalAnnualCost":26867,"size":"","strategyReco":"To be discussed","status":"","costCenter":"P66016","fundingOrigin":3,"financialSustainability":2,"keepLightsOn":2,"strategicPositioning":2,"geographicReachScore":2,"currentHumReach":3,"potentialFutureValue":1,"comments":"CRM is needed","interviewerComments":"","userNotes":""},
{"id":84,"name":"NS Investment Dashboard","description":"Strategic data-driven resource allocation tool","category":"Product","archetype":"IFRC Strategic & Operational Coord.","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"MsSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"NSDC","interviewStatus":"Completed","mau":90,"frequencyOfUse":"","primaryUserType":"","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":365833,"size":"S","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":3,"financialSustainability":2,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":3,"currentHumReach":2,"potentialFutureValue":1,"comments":"","interviewerComments":"","userNotes":""},
{"id":26,"name":"Drupal (Multiple sites)","description":"Technology behind multiple sites including ifrc.org","category":"Website","archetype":"Internal Management","subClassification":"Open Source Software","appTechnology":"PHP","database":"MySQL","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Multiple","interviewStatus":"Scheduled","mau":500000,"frequencyOfUse":"Daily","primaryUserType":"Secretariat, NS, public","geographicReach":"","portfolio":"Secretariat","department":"","totalAnnualCost":149972,"size":"","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":2,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":1,"potentialFutureValue":2,"comments":"","interviewerComments":"Contains www.ifrc.org","userNotes":""},
{"id":71,"name":"IFRCjobs (Lumesse)","description":"Recruitment Portal","category":"App","archetype":"Internal Management","subClassification":"Software As A Service","appTechnology":"Lumesse Talentlink","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"HR - Gabor/Edwin","interviewStatus":"Completed","mau":0,"frequencyOfUse":"daily","primaryUserType":"IFRC Staff","geographicReach":"90+ delegations","portfolio":"Secretariat","department":"","totalAnnualCost":115309,"size":"L","strategyReco":"Keep","status":"","costCenter":"C00286","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":1,"comments":"Face of the organization","interviewerComments":"","userNotes":""},
{"id":83,"name":"MSM","description":"ITSM Ticketing System","category":"App","archetype":"Internal Management","subClassification":"IT Service Management","appTechnology":"","database":"","dtdOwner":"Operations unit - Istvan","businessOwner":"DTD - Juriaan","interviewStatus":"Completed","mau":2500,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"Digital Transformation Department","totalAnnualCost":92833,"size":"M","strategyReco":"Keep","status":"","costCenter":"C00557","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":3,"geographicReachScore":2,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":73,"name":"Intranet (Our IFRC)","description":"Intranet on SharePoint","category":"Product","archetype":"Internal Management","subClassification":"Standard Software","appTechnology":"Sharepoint","database":"MsSQL","dtdOwner":"Digital unit-Emmanuelle","businessOwner":"Communications - Vianka Olivero","interviewStatus":"Completed","mau":2353,"frequencyOfUse":"Daily","primaryUserType":"Secretariat staff","geographicReach":"Global","portfolio":"Secretariat","department":"","totalAnnualCost":107833,"size":"","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":2,"strategicPositioning":1,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":3,"comments":"","interviewerComments":"","userNotes":""},
{"id":28,"name":"eContracts","description":"Contracts Management","category":"Product","archetype":"Internal Management","subClassification":"Be-Spoke Software","appTechnology":".Net","database":"MsSQL","dtdOwner":"Operations unit - Istvan","businessOwner":"Office of General Counsel","interviewStatus":"Completed","mau":3000,"frequencyOfUse":"Daily","primaryUserType":"Secretariat Staff","geographicReach":"Global","portfolio":"Secretariat","department":"Legal","totalAnnualCost":89833,"size":"","strategyReco":"Keep","status":"","costCenter":"C","fundingOrigin":1,"financialSustainability":3,"keepLightsOn":1,"strategicPositioning":2,"geographicReachScore":1,"currentHumReach":2,"potentialFutureValue":2,"comments":"","interviewerComments":"","userNotes":""}
];

const CATEGORIES = ["Product","App","Service","Website","Tool","Project","Programme","Request","Request for exisitng"];
const ARCHETYPES = ["Direct Community & Humanitarian Impact","Internal Management","IFRC Strategic & Operational Coord.","Humanitarian Diplomacy & Positioning","IFRC Agility & Decision-Support"];
const SUB_CLASSIFICATIONS = ["Software As A Service","Be-Spoke Software","Productivity Tools","Standard Software","Reporting","Off the Shelf Software","Open Source Software","Platform as a Service","Infrastructure","IT Service Management","Development Framework","Interfaces"];
const PORTFOLIOS = ["Secretariat","IFRC Network","Membership"];
const STRATEGY_RECOS = ["Keep","To be discussed","Divest","Terminate","Essential","Cancel (request)","Remove from list"];
const STATUSES = ["Live / Operational","To be retired","To be removed","Identified","Planned","In Dev.",""];

const PIE_COLORS = ["#e11d48","#0ea5e9","#8b5cf6","#14b8a6","#f59e0b","#ec4899","#10b981","#64748b","#f97316"];
const scoreColor = v => v===1?"#16a34a":v===2?"#d97706":v===3?"#dc2626":"#475569";
const scoreLabel = v => v===1?"High":v===2?"Medium":v===3?"Low":"N/A";
const strategyColor = s => ({"Keep":"#16a34a","Essential":"#059669","To be discussed":"#d97706","Divest":"#ea580c","Terminate":"#dc2626","Cancel (request)":"#dc2626","Remove from list":"#9ca3af"})[s]||"#64748b";
const formatCHF = n => n==null||isNaN(n)?"—":`CHF ${n.toLocaleString("de-CH")}`;

const ScoreBadge = ({value}) => <span style={{display:"inline-flex",alignItems:"center",gap:4,padding:"2px 8px",borderRadius:4,fontSize:11,fontWeight:600,background:`${scoreColor(value)}18`,color:scoreColor(value),border:`1px solid ${scoreColor(value)}30`}}><span style={{width:6,height:6,borderRadius:"50%",background:scoreColor(value)}}/>{scoreLabel(value)}</span>;
const StrategyBadge = ({value}) => <span style={{padding:"3px 10px",borderRadius:4,fontSize:11,fontWeight:700,letterSpacing:"0.02em",background:`${strategyColor(value)}15`,color:strategyColor(value),border:`1px solid ${strategyColor(value)}30`,textTransform:"uppercase"}}>{value||"—"}</span>;
const CategoryPill = ({value}) => {const c=({"Product":"#6366f1","App":"#0ea5e9","Service":"#8b5cf6","Website":"#14b8a6","Tool":"#f59e0b","Project":"#ec4899","Programme":"#10b981","Request":"#64748b","Request for exisitng":"#f97316"})[value]||"#64748b";return <span style={{padding:"2px 10px",borderRadius:20,fontSize:11,fontWeight:600,background:`${c}12`,color:c,border:`1px solid ${c}25`}}>{value}</span>};

const inputStyle = {width:"100%",padding:"9px 12px",background:"#1e293b",border:"1px solid #334155",borderRadius:8,color:"#f1f5f9",fontSize:13,fontFamily:"'DM Sans',sans-serif",outline:"none",boxSizing:"border-box"};
const selectStyle = {...inputStyle,appearance:"none",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%2394a3b8' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'/%3E%3C/svg%3E\")",backgroundRepeat:"no-repeat",backgroundPosition:"right 12px center",paddingRight:32};

function Modal({open,onClose,title,children,width=720}) {
  if(!open) return null;
  return <div style={{position:"fixed",inset:0,zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={onClose}>
    <div style={{position:"absolute",inset:0,background:"rgba(2,6,23,0.6)",backdropFilter:"blur(4px)"}}/>
    <div onClick={e=>e.stopPropagation()} style={{position:"relative",background:"#0f172a",borderRadius:16,border:"1px solid #1e293b",width:"90%",maxWidth:width,maxHeight:"88vh",overflow:"auto",boxShadow:"0 25px 50px rgba(0,0,0,0.5)"}}>
      <div style={{position:"sticky",top:0,zIndex:2,display:"flex",justifyContent:"space-between",alignItems:"center",padding:"20px 28px 16px",background:"#0f172a",borderBottom:"1px solid #1e293b"}}>
        <h2 style={{margin:0,fontSize:18,fontWeight:700,color:"#f1f5f9"}}>{title}</h2>
        <button onClick={onClose} style={{background:"none",border:"none",color:"#64748b",fontSize:22,cursor:"pointer",padding:"4px 8px",borderRadius:6}}>✕</button>
      </div>
      <div style={{padding:"20px 28px 28px"}}>{children}</div>
    </div>
  </div>;
}

function FormField({label,children}) {
  return <div style={{marginBottom:16}}><label style={{display:"block",fontSize:11,fontWeight:600,color:"#94a3b8",marginBottom:5,letterSpacing:"0.03em"}}>{label}</label>{children}</div>;
}

function ItemForm({item,onSave,onCancel}) {
  const [f,setF] = useState(item||{name:"",description:"",category:"Product",archetype:ARCHETYPES[0],subClassification:SUB_CLASSIFICATIONS[0],appTechnology:"",database:"",dtdOwner:"",businessOwner:"",interviewStatus:"Completed",mau:0,frequencyOfUse:"",primaryUserType:"",geographicReach:"Global",portfolio:PORTFOLIOS[0],department:"",totalAnnualCost:0,size:"M",strategyReco:STRATEGY_RECOS[0],status:STATUSES[0],costCenter:"",fundingOrigin:2,financialSustainability:2,keepLightsOn:2,strategicPositioning:2,geographicReachScore:2,currentHumReach:2,potentialFutureValue:2,comments:"",interviewerComments:"",userNotes:""});
  const u = (k,v) => setF(p=>({...p,[k]:v}));
  return <div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 20px"}}>
      <FormField label="NAME *"><input style={inputStyle} value={f.name} onChange={e=>u("name",e.target.value)}/></FormField>
      <FormField label="CATEGORY"><select style={selectStyle} value={f.category} onChange={e=>u("category",e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></FormField>
    </div>
    <FormField label="DESCRIPTION"><textarea style={{...inputStyle,minHeight:60,resize:"vertical"}} value={f.description} onChange={e=>u("description",e.target.value)}/></FormField>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 20px"}}>
      <FormField label="ARCHETYPE"><select style={selectStyle} value={f.archetype} onChange={e=>u("archetype",e.target.value)}>{ARCHETYPES.map(a=><option key={a}>{a}</option>)}</select></FormField>
      <FormField label="SUB-CLASSIFICATION"><select style={selectStyle} value={f.subClassification} onChange={e=>u("subClassification",e.target.value)}>{SUB_CLASSIFICATIONS.map(s=><option key={s}>{s}</option>)}</select></FormField>
      <FormField label="APP TECHNOLOGY"><input style={inputStyle} value={f.appTechnology} onChange={e=>u("appTechnology",e.target.value)}/></FormField>
      <FormField label="DATABASE"><input style={inputStyle} value={f.database} onChange={e=>u("database",e.target.value)}/></FormField>
      <FormField label="DTD OWNER"><input style={inputStyle} value={f.dtdOwner} onChange={e=>u("dtdOwner",e.target.value)}/></FormField>
      <FormField label="BUSINESS OWNER"><input style={inputStyle} value={f.businessOwner} onChange={e=>u("businessOwner",e.target.value)}/></FormField>
    </div>
    <div style={{borderTop:"1px solid #1e293b",paddingTop:12,marginTop:8}}>
      <div style={{fontSize:13,fontWeight:700,color:"#cbd5e1",marginBottom:14}}>Usage & Reach</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"0 20px"}}>
        <FormField label="MAU"><input style={inputStyle} type="number" value={f.mau} onChange={e=>u("mau",parseInt(e.target.value)||0)}/></FormField>
        <FormField label="FREQUENCY"><input style={inputStyle} value={f.frequencyOfUse} onChange={e=>u("frequencyOfUse",e.target.value)}/></FormField>
        <FormField label="PRIMARY USERS"><input style={inputStyle} value={f.primaryUserType} onChange={e=>u("primaryUserType",e.target.value)}/></FormField>
        <FormField label="GEOGRAPHIC REACH"><input style={inputStyle} value={f.geographicReach} onChange={e=>u("geographicReach",e.target.value)}/></FormField>
        <FormField label="PORTFOLIO"><select style={selectStyle} value={f.portfolio} onChange={e=>u("portfolio",e.target.value)}>{PORTFOLIOS.map(p=><option key={p}>{p}</option>)}</select></FormField>
        <FormField label="DEPARTMENT"><input style={inputStyle} value={f.department} onChange={e=>u("department",e.target.value)}/></FormField>
      </div>
    </div>
    <div style={{borderTop:"1px solid #1e293b",paddingTop:12,marginTop:8}}>
      <div style={{fontSize:13,fontWeight:700,color:"#cbd5e1",marginBottom:14}}>Financials & Strategy</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"0 20px"}}>
        <FormField label="ANNUAL COST (CHF)"><input style={inputStyle} type="number" value={f.totalAnnualCost} onChange={e=>u("totalAnnualCost",parseInt(e.target.value)||0)}/></FormField>
        <FormField label="SIZE"><select style={selectStyle} value={f.size} onChange={e=>u("size",e.target.value)}>{["S","M","L",""].map(s=><option key={s} value={s}>{s||"—"}</option>)}</select></FormField>
        <FormField label="STATUS"><select style={selectStyle} value={f.status} onChange={e=>u("status",e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s||"—"}</option>)}</select></FormField>
      </div>
      <FormField label="STRATEGY RECOMMENDATION"><select style={selectStyle} value={f.strategyReco} onChange={e=>u("strategyReco",e.target.value)}>{STRATEGY_RECOS.map(s=><option key={s}>{s}</option>)}</select></FormField>
    </div>
    <div style={{borderTop:"1px solid #1e293b",paddingTop:12,marginTop:8}}>
      <div style={{fontSize:13,fontWeight:700,color:"#cbd5e1",marginBottom:14}}>Assessment Scores (1=High, 2=Medium, 3=Low)</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"0 16px"}}>
        {[["fundingOrigin","Funding Origin"],["financialSustainability","Financial Sust."],["keepLightsOn","Keep Lights On"],["strategicPositioning","Strategic Pos."],["geographicReachScore","Geographic"],["currentHumReach","Hum. Impact"],["potentialFutureValue","Future Value"]].map(([k,l])=>
          <FormField key={k} label={l.toUpperCase()}><select style={selectStyle} value={f[k]} onChange={e=>u(k,parseInt(e.target.value))}><option value={1}>1 – High</option><option value={2}>2 – Medium</option><option value={3}>3 – Low</option></select></FormField>
        )}
      </div>
    </div>
    <div style={{borderTop:"1px solid #1e293b",paddingTop:12,marginTop:8}}>
      <div style={{fontSize:13,fontWeight:700,color:"#cbd5e1",marginBottom:14}}>Notes & Comments</div>
      <FormField label="YOUR NOTES"><textarea style={{...inputStyle,minHeight:80,resize:"vertical"}} value={f.userNotes||""} onChange={e=>u("userNotes",e.target.value)} placeholder="Add your own notes here..."/></FormField>
    </div>
    <div style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:20,paddingTop:16,borderTop:"1px solid #1e293b"}}>
      <button onClick={onCancel} style={{padding:"9px 20px",borderRadius:8,border:"1px solid #334155",background:"transparent",color:"#94a3b8",fontSize:13,fontWeight:600,cursor:"pointer"}}>Cancel</button>
      <button onClick={()=>f.name.trim()&&onSave(f)} style={{padding:"9px 24px",borderRadius:8,border:"none",background:f.name.trim()?"#e11d48":"#334155",color:f.name.trim()?"#fff":"#64748b",fontSize:13,fontWeight:700,cursor:f.name.trim()?"pointer":"default"}}>{item?"Update":"Create"}</button>
    </div>
  </div>;
}

function DetailView({item,onEdit,onDelete,onUpdateNotes}) {
  const [notes,setNotes]=useState(item.userNotes||"");
  const [saved,setSaved]=useState(false);
  const saveNotes = () => {onUpdateNotes(item.id,notes);setSaved(true);setTimeout(()=>setSaved(false),2000);};

  const sections = [
    {title:"Classification",items:[["Category",<CategoryPill value={item.category}/>],["Archetype",item.archetype],["Sub-classification",item.subClassification],["Technology",item.appTechnology],["Database",item.database]]},
    {title:"Ownership",items:[["DTD Owner",item.dtdOwner],["Business Owner",item.businessOwner],["Portfolio",item.portfolio],["Department",item.department],["Cost Center",item.costCenter]]},
    {title:"Usage",items:[["Monthly Active Users",(item.mau||0).toLocaleString()],["Frequency",item.frequencyOfUse],["Primary Users",item.primaryUserType],["Geographic Reach",item.geographicReach]]},
    {title:"Financials",items:[["Total Annual Cost",formatCHF(item.totalAnnualCost)],["Size",item.size],["Status",item.status||"—"]]},
  ];

  return <div>
    <div style={{marginBottom:20}}>
      <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:8}}><StrategyBadge value={item.strategyReco}/><span style={{fontSize:11,color:"#64748b"}}>Strategy Recommendation</span></div>
      <p style={{color:"#94a3b8",fontSize:14,lineHeight:1.6,margin:0}}>{item.description||"No description."}</p>
    </div>
    {sections.map(s=><div key={s.title} style={{marginBottom:16}}>
      <div style={{fontSize:11,fontWeight:700,color:"#475569",letterSpacing:"0.08em",marginBottom:8}}>{s.title.toUpperCase()}</div>
      <div style={{background:"#1e293b",borderRadius:10,padding:"4px 0",border:"1px solid #334155"}}>
        {s.items.map(([l,v],i)=><div key={l} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 16px",borderBottom:i<s.items.length-1?"1px solid #33415520":"none"}}><span style={{fontSize:12,color:"#64748b"}}>{l}</span><span style={{fontSize:13,color:"#e2e8f0",fontWeight:500,maxWidth:"60%",textAlign:"right"}}>{v||"—"}</span></div>)}
      </div>
    </div>)}
    <div style={{marginBottom:16}}>
      <div style={{fontSize:11,fontWeight:700,color:"#475569",letterSpacing:"0.08em",marginBottom:8}}>ASSESSMENT SCORES</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>
        {[["Funding Origin",item.fundingOrigin],["Financial Sustainability",item.financialSustainability],["Keep the Lights On",item.keepLightsOn],["Strategic Positioning",item.strategicPositioning],["Geographic Reach",item.geographicReachScore],["Humanitarian Impact",item.currentHumReach],["Potential Future Value",item.potentialFutureValue]].map(([l,v])=>
          <div key={l} style={{display:"flex",justifyContent:"space-between",alignItems:"center",background:"#1e293b",borderRadius:8,padding:"8px 14px",border:"1px solid #334155"}}><span style={{fontSize:12,color:"#94a3b8"}}>{l}</span><ScoreBadge value={v}/></div>
        )}
      </div>
    </div>
    {(item.comments||item.interviewerComments) && <div style={{marginBottom:16}}>
      <div style={{fontSize:11,fontWeight:700,color:"#475569",letterSpacing:"0.08em",marginBottom:8}}>EXISTING COMMENTS</div>
      {item.comments && <div style={{background:"#1e293b",borderRadius:8,padding:"10px 14px",border:"1px solid #334155",fontSize:12,color:"#94a3b8",lineHeight:1.6,marginBottom:8}}>{item.comments}</div>}
      {item.interviewerComments && <div style={{background:"#1e293b",borderRadius:8,padding:"10px 14px",border:"1px solid #334155",fontSize:12,color:"#94a3b8",lineHeight:1.6}}><span style={{color:"#64748b",fontWeight:600}}>Interviewer: </span>{item.interviewerComments}</div>}
    </div>}
    <div style={{marginBottom:16}}>
      <div style={{fontSize:11,fontWeight:700,color:"#475569",letterSpacing:"0.08em",marginBottom:8}}>YOUR NOTES</div>
      <textarea style={{...inputStyle,minHeight:80,resize:"vertical"}} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add your notes here..."/>
      <div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><button onClick={saveNotes} style={{padding:"6px 16px",borderRadius:6,border:"none",background:saved?"#16a34a":"#334155",color:"#fff",fontSize:12,fontWeight:600,cursor:"pointer"}}>{saved?"✓ Saved":"Save Notes"}</button></div>
    </div>
    <div style={{display:"flex",justifyContent:"space-between",marginTop:24,paddingTop:16,borderTop:"1px solid #1e293b"}}>
      <button onClick={onDelete} style={{padding:"8px 18px",borderRadius:8,border:"1px solid #7f1d1d",background:"transparent",color:"#f87171",fontSize:13,fontWeight:600,cursor:"pointer"}}>Delete</button>
      <button onClick={onEdit} style={{padding:"8px 24px",borderRadius:8,border:"none",background:"#e11d48",color:"#fff",fontSize:13,fontWeight:700,cursor:"pointer"}}>Edit</button>
    </div>
  </div>;
}

const CustomTooltip = ({active,payload,label}) => {
  if(!active||!payload?.length) return null;
  return <div style={{background:"#1e293b",border:"1px solid #334155",borderRadius:8,padding:"8px 12px",fontSize:12,color:"#e2e8f0"}}><div style={{fontWeight:600,marginBottom:4}}>{label||payload[0].name}</div>{payload.map((p,i)=><div key={i} style={{color:p.color||p.fill}}>{p.name}: {typeof p.value==="number"?p.value.toLocaleString():p.value}</div>)}</div>;
};

export default function App() {
  const [data,setData]=useState(INITIAL_DATA);
  const [search,setSearch]=useState("");
  const [fCat,setFCat]=useState("All");
  const [fArch,setFArch]=useState("All");
  const [fStrat,setFStrat]=useState("All");
  const [fPort,setFPort]=useState("All");
  const [sortKey,setSortKey]=useState("name");
  const [sortDir,setSortDir]=useState("asc");
  const [view,setView]=useState("table");
  const [modal,setModal]=useState(null);
  const [sel,setSel]=useState(null);
  const [nextId,setNextId]=useState(200);

  const filtered = useMemo(()=>{
    let d=data.filter(i=>{
      if(search && !i.name.toLowerCase().includes(search.toLowerCase()) && !i.description.toLowerCase().includes(search.toLowerCase())) return false;
      if(fCat!=="All" && i.category!==fCat) return false;
      if(fArch!=="All" && i.archetype!==fArch) return false;
      if(fStrat!=="All" && i.strategyReco!==fStrat) return false;
      if(fPort!=="All" && i.portfolio!==fPort) return false;
      return true;
    });
    d.sort((a,b)=>{let av=a[sortKey],bv=b[sortKey];if(typeof av==="string")av=av.toLowerCase();if(typeof bv==="string")bv=bv.toLowerCase();return av<bv?(sortDir==="asc"?-1:1):av>bv?(sortDir==="asc"?1:-1):0;});
    return d;
  },[data,search,fCat,fArch,fStrat,fPort,sortKey,sortDir]);

  const stats = useMemo(()=>{
    const totalCost=data.reduce((s,i)=>s+(i.totalAnnualCost||0),0);
    const totalMAU=data.reduce((s,i)=>s+(i.mau||0),0);
    const byCat={},byStrat={},byArch={},byPort={};
    data.forEach(i=>{byCat[i.category]=(byCat[i.category]||0)+1;byStrat[i.strategyReco]=(byStrat[i.strategyReco]||0)+1;byArch[i.archetype]=(byArch[i.archetype]||0)+1;byPort[i.portfolio]=(byPort[i.portfolio]||0)+1;});
    const costByCat={},costByStrat={};
    data.forEach(i=>{costByCat[i.category]=(costByCat[i.category]||0)+(i.totalAnnualCost||0);costByStrat[i.strategyReco]=(costByStrat[i.strategyReco]||0)+(i.totalAnnualCost||0);});
    return {totalCost,totalMAU,count:data.length,byCat,byStrat,byArch,byPort,costByCat,costByStrat};
  },[data]);

  const handleSort = k => {if(sortKey===k) setSortDir(d=>d==="asc"?"desc":"asc"); else {setSortKey(k);setSortDir("asc");}};
  const handleCreate = f => {setData(p=>[...p,{...f,id:nextId}]);setNextId(n=>n+1);setModal(null);};
  const handleUpdate = f => {setData(p=>p.map(i=>i.id===f.id?f:i));setSel(f);setModal("detail");};
  const handleDelete = id => {setData(p=>p.filter(i=>i.id!==id));setModal(null);setSel(null);};
  const handleUpdateNotes = (id,notes) => {setData(p=>p.map(i=>i.id===id?{...i,userNotes:notes}:i));};

  const exportCSV = () => {
    const headers=["Name","Category","Archetype","Sub-Classification","Portfolio","Department","MAU","Annual Cost (CHF)","Strategy Reco","Status","DTD Owner","Business Owner","Technology","Database","Funding Origin","Financial Sustainability","Keep Lights On","Strategic Positioning","Geographic Reach Score","Humanitarian Impact","Future Value","User Notes"];
    const rows=filtered.map(i=>[i.name,i.category,i.archetype,i.subClassification,i.portfolio,i.department,i.mau,i.totalAnnualCost,i.strategyReco,i.status,i.dtdOwner,i.businessOwner,i.appTechnology,i.database,scoreLabel(i.fundingOrigin),scoreLabel(i.financialSustainability),scoreLabel(i.keepLightsOn),scoreLabel(i.strategicPositioning),scoreLabel(i.geographicReachScore),scoreLabel(i.currentHumReach),scoreLabel(i.potentialFutureValue),i.userNotes||""].map(v=>`"${String(v||"").replace(/"/g,'""')}"`));
    const csv=[headers.join(","),...rows.map(r=>r.join(","))].join("\n");
    const blob=new Blob([csv],{type:"text/csv"});
    const url=URL.createObjectURL(blob);
    const a=document.createElement("a");a.href=url;a.download=`ifrc-portfolio-export-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);
  };

  const SortHeader = ({k,children}) => <th onClick={()=>handleSort(k)} style={{padding:"10px 12px",textAlign:"left",fontSize:11,fontWeight:700,color:"#64748b",letterSpacing:"0.06em",cursor:"pointer",userSelect:"none",whiteSpace:"nowrap",borderBottom:"1px solid #1e293b",position:"sticky",top:0,background:"#0c1322",zIndex:1}}>{children}{sortKey===k?(sortDir==="asc"?" ↑":" ↓"):""}</th>;

  const pieData = Object.entries(stats.byCat).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);
  const stratPieData = Object.entries(stats.byStrat).filter(([k])=>k).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);
  const costBarData = Object.entries(stats.costByCat).map(([name,value])=>({name:name.length>12?name.slice(0,12)+"…":name,value})).sort((a,b)=>b.value-a.value);
  const archData = Object.entries(stats.byArch).map(([name,value])=>({name:name.length>20?name.slice(0,20)+"…":name,value}));
  const top10Cost = [...data].sort((a,b)=>(b.totalAnnualCost||0)-(a.totalAnnualCost||0)).slice(0,10);
  const avgScores = useMemo(()=>{
    const keys=["fundingOrigin","financialSustainability","keepLightsOn","strategicPositioning","geographicReachScore","currentHumReach","potentialFutureValue"];
    const labels=["Funding","Fin. Sust.","KTLO","Strategic","Geographic","Hum. Impact","Future Value"];
    const validItems=data.filter(i=>keys.some(k=>i[k]>0));
    return keys.map((k,i)=>({subject:labels[i],value:validItems.length?+(validItems.reduce((s,it)=>s+(it[k]||0),0)/validItems.length).toFixed(2):0}));
  },[data]);

  return <div style={{fontFamily:"'DM Sans',sans-serif",background:"#020617",color:"#e2e8f0",minHeight:"100vh"}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;900&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"/>

    <div style={{background:"linear-gradient(135deg,#0f172a 0%,#1e1030 100%)",borderBottom:"1px solid #1e293b"}}>
      <div style={{maxWidth:1400,margin:"0 auto",padding:"20px 32px",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
        <div>
          <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:4}}>
            <div style={{width:32,height:32,background:"#e11d48",borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:900,color:"#fff"}}>⬡</div>
            <h1 style={{margin:0,fontSize:22,fontWeight:900,color:"#f8fafc",letterSpacing:"-0.02em"}}>IFRC Portfolio Registry</h1>
          </div>
          <p style={{margin:0,fontSize:13,color:"#64748b",marginLeft:44}}>Enterprise Architecture · {data.length} Products, Services & Applications</p>
        </div>
        <div style={{display:"flex",gap:10}}>
          <button onClick={exportCSV} style={{display:"flex",alignItems:"center",gap:6,padding:"10px 18px",borderRadius:10,border:"1px solid #334155",background:"transparent",color:"#94a3b8",fontSize:13,fontWeight:600,cursor:"pointer"}}>⬇ Export CSV</button>
          <button onClick={()=>{setSel(null);setModal("create")}} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 22px",borderRadius:10,border:"none",background:"#e11d48",color:"#fff",fontSize:13,fontWeight:700,cursor:"pointer",boxShadow:"0 4px 12px rgba(225,29,72,0.3)"}}><span style={{fontSize:18,lineHeight:1}}>+</span> New Item</button>
        </div>
      </div>
    </div>

    <div style={{maxWidth:1400,margin:"0 auto",padding:"20px 32px"}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:16,marginBottom:20}}>
        {[["Total Items",stats.count,"📦"],["Total Annual Cost",formatCHF(stats.totalCost),"💰"],["Total MAU",stats.totalMAU.toLocaleString(),"👥"],["Filtered",filtered.length+" shown","🔍"]].map(([l,v,icon])=>
          <div key={l} style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:"16px 20px",display:"flex",alignItems:"center",gap:14}}>
            <div style={{width:40,height:40,borderRadius:10,background:"#1e293b",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>{icon}</div>
            <div><div style={{fontSize:11,color:"#64748b",fontWeight:600,letterSpacing:"0.04em"}}>{l.toUpperCase()}</div><div style={{fontSize:18,fontWeight:800,color:"#f1f5f9",fontFamily:"'Space Mono',monospace"}}>{v}</div></div>
          </div>
        )}
      </div>

      <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:"16px 20px",marginBottom:16}}>
        <div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap"}}>
          <div style={{flex:"1 1 220px"}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." style={{...inputStyle,background:"#1e293b",fontSize:13,padding:"8px 14px"}}/></div>
          <select value={fCat} onChange={e=>setFCat(e.target.value)} style={{...selectStyle,flex:"0 0 140px",fontSize:12,padding:"8px 12px"}}><option value="All">All Categories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select>
          <select value={fArch} onChange={e=>setFArch(e.target.value)} style={{...selectStyle,flex:"0 0 180px",fontSize:12,padding:"8px 12px"}}><option value="All">All Archetypes</option>{ARCHETYPES.map(a=><option key={a}>{a}</option>)}</select>
          <select value={fStrat} onChange={e=>setFStrat(e.target.value)} style={{...selectStyle,flex:"0 0 140px",fontSize:12,padding:"8px 12px"}}><option value="All">All Strategy</option>{STRATEGY_RECOS.map(s=><option key={s}>{s}</option>)}</select>
          <select value={fPort} onChange={e=>setFPort(e.target.value)} style={{...selectStyle,flex:"0 0 140px",fontSize:12,padding:"8px 12px"}}><option value="All">All Portfolios</option>{PORTFOLIOS.map(p=><option key={p}>{p}</option>)}</select>
          <div style={{display:"flex",gap:4,background:"#1e293b",borderRadius:8,padding:3,border:"1px solid #334155"}}>
            {[["table","≡"],["grid","⊞"],["dashboard","◧"]].map(([v,icon])=><button key={v} onClick={()=>setView(v)} style={{padding:"6px 12px",borderRadius:6,border:"none",background:view===v?"#e11d48":"transparent",color:view===v?"#fff":"#64748b",fontSize:14,cursor:"pointer",fontWeight:700}}>{icon}</button>)}
          </div>
        </div>
      </div>

      {view==="table" && <div style={{background:"#0c1322",borderRadius:12,border:"1px solid #1e293b",overflow:"auto",maxHeight:600}}>
        <table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}>
          <thead><tr>
            <SortHeader k="name">NAME</SortHeader><SortHeader k="category">CATEGORY</SortHeader><SortHeader k="archetype">ARCHETYPE</SortHeader><SortHeader k="portfolio">PORTFOLIO</SortHeader><SortHeader k="mau">MAU</SortHeader><SortHeader k="totalAnnualCost">COST</SortHeader><SortHeader k="strategyReco">STRATEGY</SortHeader>
            <th style={{padding:"10px 12px",textAlign:"center",fontSize:11,fontWeight:700,color:"#64748b",borderBottom:"1px solid #1e293b",position:"sticky",top:0,background:"#0c1322",zIndex:1}}>SCORES</th>
            <th style={{padding:"10px 12px",textAlign:"center",fontSize:11,fontWeight:700,color:"#64748b",borderBottom:"1px solid #1e293b",position:"sticky",top:0,background:"#0c1322",zIndex:1}}>📝</th>
          </tr></thead>
          <tbody>{filtered.map(item=><tr key={item.id} onClick={()=>{setSel(item);setModal("detail")}} style={{cursor:"pointer",borderBottom:"1px solid #1e293b10"}} onMouseOver={e=>e.currentTarget.style.background="#1e293b40"} onMouseOut={e=>e.currentTarget.style.background="transparent"}>
            <td style={{padding:"10px 12px",fontWeight:600,color:"#f1f5f9",maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.name}</td>
            <td style={{padding:"10px 12px"}}><CategoryPill value={item.category}/></td>
            <td style={{padding:"10px 12px",fontSize:12,color:"#94a3b8",maxWidth:160,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.archetype}</td>
            <td style={{padding:"10px 12px",fontSize:12,color:"#94a3b8"}}>{item.portfolio}</td>
            <td style={{padding:"10px 12px",fontFamily:"'Space Mono',monospace",fontSize:12,color:"#cbd5e1"}}>{(item.mau||0).toLocaleString()}</td>
            <td style={{padding:"10px 12px",fontFamily:"'Space Mono',monospace",fontSize:12,color:"#cbd5e1"}}>{formatCHF(item.totalAnnualCost)}</td>
            <td style={{padding:"10px 12px"}}><StrategyBadge value={item.strategyReco}/></td>
            <td style={{padding:"10px 12px",textAlign:"center"}}><div style={{display:"flex",gap:3,justifyContent:"center"}}>{[item.keepLightsOn,item.strategicPositioning,item.currentHumReach,item.potentialFutureValue].map((v,i)=><div key={i} style={{width:8,height:8,borderRadius:"50%",background:scoreColor(v)}} title={["KTLO","Strategic","Impact","Future"][i]+": "+scoreLabel(v)}/>)}</div></td>
            <td style={{padding:"10px 12px",textAlign:"center",fontSize:12,color:item.userNotes?"#f59e0b":"#334155"}}>{item.userNotes?"●":"○"}</td>
          </tr>)}</tbody>
        </table>
        {!filtered.length && <div style={{padding:40,textAlign:"center",color:"#475569"}}>No items match your filters.</div>}
      </div>}

      {view==="grid" && <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14}}>
        {filtered.map(item=><div key={item.id} onClick={()=>{setSel(item);setModal("detail")}} style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20,cursor:"pointer",transition:"border-color 0.15s,transform 0.15s"}} onMouseOver={e=>{e.currentTarget.style.borderColor="#334155";e.currentTarget.style.transform="translateY(-2px)"}} onMouseOut={e=>{e.currentTarget.style.borderColor="#1e293b";e.currentTarget.style.transform="translateY(0)"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",marginBottom:10}}><div style={{fontSize:15,fontWeight:700,color:"#f1f5f9",lineHeight:1.3,flex:1,marginRight:8}}>{item.name}</div><CategoryPill value={item.category}/></div>
          <p style={{fontSize:12,color:"#64748b",lineHeight:1.5,margin:"0 0 12px",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.description}</p>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><StrategyBadge value={item.strategyReco}/><span style={{fontSize:12,color:"#94a3b8",fontFamily:"'Space Mono',monospace"}}>{formatCHF(item.totalAnnualCost)}</span></div>
          <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{[["KTLO",item.keepLightsOn],["Strategic",item.strategicPositioning],["Impact",item.currentHumReach],["Future",item.potentialFutureValue]].map(([l,v])=><span key={l} style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:10,color:"#64748b",background:"#1e293b",padding:"3px 8px",borderRadius:4}}><span style={{width:5,height:5,borderRadius:"50%",background:scoreColor(v)}}/>{l}</span>)}</div>
          <div style={{display:"flex",justifyContent:"space-between",marginTop:10,fontSize:11,color:"#475569"}}><span>{item.portfolio}</span><span>MAU: {(item.mau||0).toLocaleString()}</span></div>
        </div>)}
      </div>}

      {view==="dashboard" && <div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16,marginBottom:16}}>
          <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20}}>
            <div style={{fontSize:13,fontWeight:700,color:"#94a3b8",marginBottom:12}}>BY CATEGORY</div>
            <ResponsiveContainer width="100%" height={200}><PieChart><Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={75} strokeWidth={0}>{pieData.map((_,i)=><Cell key={i} fill={PIE_COLORS[i%PIE_COLORS.length]}/>)}</Pie><Tooltip content={<CustomTooltip/>}/></PieChart></ResponsiveContainer>
            <div style={{display:"flex",flexWrap:"wrap",gap:6,marginTop:8}}>{pieData.map((d,i)=><span key={d.name} style={{fontSize:10,color:"#94a3b8",display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:PIE_COLORS[i%PIE_COLORS.length]}}/>{d.name} ({d.value})</span>)}</div>
          </div>
          <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20}}>
            <div style={{fontSize:13,fontWeight:700,color:"#94a3b8",marginBottom:12}}>BY STRATEGY</div>
            <ResponsiveContainer width="100%" height={200}><PieChart><Pie data={stratPieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={75} strokeWidth={0}>{stratPieData.map((d)=><Cell key={d.name} fill={strategyColor(d.name)}/>)}</Pie><Tooltip content={<CustomTooltip/>}/></PieChart></ResponsiveContainer>
            <div style={{display:"flex",flexWrap:"wrap",gap:6,marginTop:8}}>{stratPieData.map(d=><span key={d.name} style={{fontSize:10,color:"#94a3b8",display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:strategyColor(d.name)}}/>{d.name} ({d.value})</span>)}</div>
          </div>
          <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20}}>
            <div style={{fontSize:13,fontWeight:700,color:"#94a3b8",marginBottom:12}}>AVG ASSESSMENT (lower=better)</div>
            <ResponsiveContainer width="100%" height={220}><RadarChart data={avgScores}><PolarGrid stroke="#334155"/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"#94a3b8"}}/><PolarRadiusAxis domain={[0,3]} tick={{fontSize:9,fill:"#475569"}}/><Radar dataKey="value" stroke="#e11d48" fill="#e11d48" fillOpacity={0.2}/></RadarChart></ResponsiveContainer>
          </div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20}}>
            <div style={{fontSize:13,fontWeight:700,color:"#94a3b8",marginBottom:12}}>COST BY CATEGORY (CHF)</div>
            <ResponsiveContainer width="100%" height={250}><BarChart data={costBarData} layout="vertical" margin={{left:80}}><XAxis type="number" tick={{fontSize:10,fill:"#64748b"}} tickFormatter={v=>v>=1e6?(v/1e6).toFixed(1)+"M":v>=1e3?(v/1e3).toFixed(0)+"K":v}/><YAxis type="category" dataKey="name" tick={{fontSize:11,fill:"#94a3b8"}} width={80}/><Tooltip content={<CustomTooltip/>} formatter={v=>formatCHF(v)}/><Bar dataKey="value" fill="#e11d48" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer>
          </div>
          <div style={{background:"#0f172a",borderRadius:12,border:"1px solid #1e293b",padding:20}}>
            <div style={{fontSize:13,fontWeight:700,color:"#94a3b8",marginBottom:12}}>TOP 10 BY ANNUAL COST</div>
            {top10Cost.map((item,i)=><div key={item.id} onClick={()=>{setSel(item);setModal("detail")}} style={{display:"flex",alignItems:"center",gap:10,padding:"6px 8px",marginBottom:4,borderRadius:6,cursor:"pointer"}} onMouseOver={e=>e.currentTarget.style.background="#1e293b"} onMouseOut={e=>e.currentTarget.style.background="transparent"}>
              <span style={{fontSize:11,color:"#475569",fontWeight:700,fontFamily:"'Space Mono',monospace",minWidth:18}}>{i+1}.</span>
              <span style={{flex:1,fontSize:13,color:"#e2e8f0",fontWeight:500,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.name}</span>
              <span style={{fontSize:12,color:"#e11d48",fontWeight:700,fontFamily:"'Space Mono',monospace"}}>{formatCHF(item.totalAnnualCost)}</span>
            </div>)}
          </div>
        </div>
      </div>}
    </div>

    <Modal open={modal==="create"} onClose={()=>setModal(null)} title="Add New Item" width={800}><ItemForm onSave={handleCreate} onCancel={()=>setModal(null)}/></Modal>
    <Modal open={modal==="edit"} onClose={()=>setModal(null)} title={`Edit: ${sel?.name}`} width={800}><ItemForm item={sel} onSave={handleUpdate} onCancel={()=>setModal("detail")}/></Modal>
    <Modal open={modal==="detail"} onClose={()=>setModal(null)} title={sel?.name} width={640}>{sel && <DetailView item={sel} onEdit={()=>setModal("edit")} onDelete={()=>handleDelete(sel.id)} onUpdateNotes={handleUpdateNotes}/>}</Modal>
  </div>;
}
